behaviors:
  EnvironmentAgentBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
      vis_encode_type: match3
      #memory:
        #sequence_length: 64
        #memory_size: 64
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
   
     # curiosity:
     #   strength: 0.02
     #   gamma: 0.99
     #   encoding_size: 256
     #   learning_rate: 3.0e-4
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 10000
  #  self_play:
  #    save_steps: 50000
  #    team_change: 200000
  #    swap_steps: 2000
  #    window: 10
   #   play_against_latest_model_ratio: 0.5
   #initial_elo: 1200.0

engine_settings:
    width: 640
    height: 480
        #quality_level: 5
    time_scale: 20
        #target_frame_rate: -1
        #capture_frame_rate: 60
        #no_graphics: false

environment_parameters:
  lesson_index:
    curriculum:
      - name: Lesson0 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: EnvironmentAgentBehavior
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.75
        value: 0
      - name: Lesson1 # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: EnvironmentAgentBehavior
          signal_smoothing: true
          min_lesson_length: 100
          threshold:  0.75
        value: 1
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: EnvironmentAgentBehavior
          signal_smoothing: true
          min_lesson_length: 100
          threshold:  0.75
        value: 2
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: EnvironmentAgentBehavior
          signal_smoothing: true
          min_lesson_length: 100
          threshold:  0.75
        value: 3
      - name: Lesson4
        completion_criteria:
          measure: reward
          behavior: EnvironmentAgentBehavior
          signal_smoothing: true
          min_lesson_length: 100
          threshold:  0.75
        value: 4
      - name: Lesson5
        value: 5




